### ISSUE TITLE
swiWaitForVBlank and swiIntrWait not functioning

### ISSUE THREAD

**Issue by Drenn1** [devkitPro/libnds#16]
At some point in the past (not sure when), swiIntrWait(0, 1) stopped working in ds mode. (It should wait for a vblank interrupt if it has not occurred yet.) It never worked in dsi mode. I already had a workaround for this, using swiWaitForVBlank instead, so I just used that in both dsi mode and regular mode.

After commit 469c168d7ed86c2cbea3890595c2bae0bb7f7b65, swiWaitForVBlank doesn't work either, in any mode. It's weird, because the logic in that commit is the reverse of my experience (swiIntrWait was the one that was broken, swiWaitForVBlank worked in both modes).

I don't mean to discredit your work, fincs... =P

**Comment by fincs** [comment]
The real issue is that libnds' swiIntrWait reimplementation is broken, and it has been broken for [several years now](https://github.com/devkitPro/libnds/commit/1c964c74b4e1f88bc50cba7f75004bf2d0f3bbc4). My change merely switched swiWaitForVBlank to use our swiIntrWait instead of the BIOS' own implementation, which in turn is broken in DSi mode.

Also, no offense taken ;)

**Comment by WinterMute** [comment]
And fixed with https://github.com/devkitPro/libnds/commit/e470919065eee5573db17cb566502421ecaacfff
