### ISSUE TITLE
Add REG_MBK declaration

### ISSUE THREAD

**Issue by ahezard** [devkitPro/libnds#20]
http://problemkaputt.de/gbatek.htm#dsinewsharedwramforarm7arm9dsp

**Comment by fincs** [comment]
https://github.com/devkitPro/libnds/blob/master/include/nds/memory.h#L48

**Comment by ahezard** [comment]
Is this part of latest libnds release?

**Comment by fincs** [comment]
Yes.

**Comment by ahezard** [comment]
Ok I was not using the correct name. Thanks for the feedback.

**Comment by WinterMute** [comment]
If you need some help with this stuff please ask on IRC or the forums.

We **will** be looking into providing a function in libnds that resets the card slot. Not 100% sure about the cleanest way to do it just yet - needs some more testing yet.

I upstreamed some changes that get NitroHax building & working with devkitARM r46. It seems to be mostly working in DS mode but I haven't had the time to look at what happens if it's booted in DSi mode from nds-hb-menu yet.
