### ISSUE TITLE
Avoid nand init by default

### ISSUE THREAD

**Issue by ahezard** [devkitPro/libnds#22]
Would it be possible to avoid nand init by default? That beaks no$gba dsi mode, this is useless to most homebrew that needs only need sd access and I prefer also to not touch nand at all for safety reason

**Comment by WinterMute** [comment]
If code that functions perfectly well on hardware breaks when run on an emulator then the emulator is at fault. This issue should be reported to Martin rather than here.

Having said that, we've been testing a lot of the DSi support code in no$ locally and it works fine for us.

**Comment by ahezard** [comment]
Same as the other issue you are forcing me to maintain my fork.

**Comment by WinterMute** [comment]
Stop making threats and engage with the process. The libnds startup code doesn't break our code and I don't see any reason why it should break yours.

Maintaining inappropriate forks and advising people to use them instead of the official distribution **damages** the entire community. It doesn't help anyone if you change things to suit yourself with no consideration for anyone else or the method they're using to run code.

I would point out that everything built with current libnds runs perfectly well in DS mode, in DSi mode from various entry points on both DSi and 3DS hardware. Several of the changes you made break everything except your particular method of running your particular application.

**Comment by ahezard** [comment]
??? I am not making any "threat", I am very factual here. Stop being paranoid and over reacting. I have nothing against you and I respect your work. By the way I am not damaging the community, it is already dead, I am one of the last active libnds user and the only one that uses dsi features. But fine, I you think I am wrong, do as you want and I will do the same.

**Comment by ahezard** [comment]
And about the fact that it breaks only my code :
![hbmenu_0_6_nogba](https://cloud.githubusercontent.com/assets/16766068/23096542/420e2618-f61f-11e6-8d5a-58eda2c10b07.jpg)

And the incriminated code is nonsensical for me SDMMC_SD_START -> nand INIT:
    case SDMMC_SD_START:
        if (sdmmc_read16(REG_SDSTATUS0) == 0) {
            result = 1;
        } else {
            sdmmc_controller_init();
            sdmmc_nand_init();
            result = sdmmc_sdcard_init();
        }
        break;
